---
- name: Create DNS record at Route53
  route53:
    state: present
    zone: "{{ pd_aws_zone }}"
    record: "{{ item }}.{{ pd_public_domain }}"
    type: A
    ttl: 120
    value: "{{ pd_public_ip }}"
    wait: yes
    aws_access_key: "{{ pd_aws_access_key }}"
    aws_secret_key: "{{ pd_aws_secret_key }}"
  with_items:
    - api
    - '*.apps'
  tags:
    - public_dns
  when: (pd_public_ip is defined) and (pd_public_ip|length > 0)

- name: Create IPv6 DNS record at Route53
  route53:
    state: present
    zone: "{{ pd_aws_zone }}"
    record: "{{ item }}.{{ pd_public_domain }}"
    type: AAAA
    ttl: 120
    value: "{{ pd_public_ipv6 }}"
    wait: yes
    aws_access_key: "{{ pd_aws_access_key }}"
    aws_secret_key: "{{ pd_aws_secret_key }}"
  with_items:
    - api
    - '*.apps'
  tags:
    - public_dns
  when: (pd_public_ipv6 is defined) and (pd_public_ipv6|length > 0)
