---
- name: define base uri
  ansible.builtin.set_fact:
    robot_base: https://robot-ws.your-server.de/
    needs_reprovision: False

- name: "Retrieve current setup of {{ hetzner_ip }}"
  ansible.builtin.gather_facts:
  register: host_facts

- ansible.builtin.set_fact:
    needs_reprovision: True
  when:
    - host_facts.ansible_facts.ansible_cmdline.BOOT_IMAGE is match("rescue") or hetzner_force_provisioning == true

- name: Provision server
  include_tasks: deploy-centos-streams.yml
  when: needs_reprovision == True

- name: Add additional storage device
  ansible.builtin.include_tasks: create_additional_storage.yml
  when: hetzner_additional_disks is defined
- name: Check ansible_python_interpreter
  ansible.builtin.shell: "which python3"
  register: rc
  ignore_errors: true

- name: Set ansible_python_interpreter to /usr/libexec/platform-python (RHEL 8)
  set_fact:
    ansible_python_interpreter: /usr/libexec/platform-python
  when: rc.failed

- name: Disable password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication yes'
    line: 'PasswordAuthentication no'
  notify:
    - Restart SSH daemon
